version: '3'

services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: Pa55w0rd
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:v0.47.9
    ports:
      - "3000:3000"

volumes:
  mongodb:
  postgres: