INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10000, 'A big user story that needs to be broken down. Created by Jira Software - do not edit or delete.', 'Epic', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10001, 'Stories track functionality or features expressed as user goals.', 'Story', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10002, 'A task that needs to be done.', 'Task', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10003, 'The sub-task of the issue', 'Sub-task', true);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10004, 'jira.translation.issuetype.bug.name.desc', 'Bug', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10006, 'For system outages or incidents. Created by Jira Service Desk.', 'Incidente', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10007, 'Created by Jira Service Desk.', 'Service Request', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10008, 'For requests that require approval. Created by Jira Service Desk', 'Service Request with Approvals', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10009, 'Created by Jira Service Desk.', 'Change', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10010, 'Track underlying causes of incidents. Created by Jira Service Desk.', 'Problem', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10019, 'Uma tarefa que precisa ser executada.', 'Tarefa', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10020, 'A subtarefa do evento', 'Subtarefa', true);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10021, 'Para problemas e dúvidas gerais de TI. Criado pelo JIRA Service Desk.', 'Dúvidas', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10022, 'As histórias acompanham a funcionalidade ou os recursos expressos como objetivos do utilizador.', 'História', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10061, 'Um novo recurso do produto, que ainda tem de ser desenvolvido.', 'Novo recurso', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10062, 'Para eventos com suporte ao cliente. Criado pela Central de Atendimento JIRA.', 'Suporte', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10067, 'As tarefas monitoram partes pequenas e distintas do trabalho.', 'Tarefa', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10068, 'Os epics monitoram coleções de tarefas, histórias e bugs relacionados.', 'Epic', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10069, 'As subtarefas monitoram pequenas partes do trabalho que fazem parte de uma tarefa maior.', 'Subtarefa', true);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10087, 'As tarefas monitoram partes pequenas e distintas do trabalho.', 'Tarefa', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10088, 'Os epics monitoram coleções de tarefas, histórias e bugs relacionados.', 'Epic', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10089, 'As subtarefas monitoram pequenas partes do trabalho que fazem parte de uma tarefa maior.', 'Subtarefa', true);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10090, 'Uma melhoria ou aprimoramento de um recurso ou tarefa existente.', 'Melhoria', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10093, 'Para interrupções do sistema ou incidentes. Criado pelo Jira Service Management.', '[System] Incidente', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10094, 'Uma solicitação que segue fluxos de trabalho de ITSM.', '[System] Solicitação de serviço', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10095, 'Uma solicitação que segue fluxos de trabalho de ITSM.', '[System] Solicitação de serviço com aprovações', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10096, 'Criado pelo Jira Service Management.', '[System] Mudança', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10097, 'Controla as causas subjacentes dos incidentes. Criado pelo Jira Service Management.', '[System] Problema', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10104, 'Requisito não-funcional', 'Requisito não-funcional', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10105, 'Sub-bug', 'Sub-bug', true);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10106, '', 'Enabler', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10107, '', 'Sub-Block', true);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10108, '', 'Feature', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10109, '', 'Defect', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10113, 'Issue type utilizada para provas de conceitos de soluções técnicas', 'Discovery', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10124, 'Epics track collections of related bugs, stories, and tasks.', 'Epic', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10127, 'Subtasks track small pieces of work.', 'Subtask', true);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10128, 'Stories track functionality or features expressed as user goals.', 'Story', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10129, 'Tasks track small, distinct pieces of work.', 'Task', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10130, 'Bugs track problems or errors.', 'Bug', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10131, 'As tarefas monitoram partes pequenas e distintas do trabalho.', 'Tarefa', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10132, 'Epics track collections of related bugs, stories, and tasks.', 'Epic', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10133, 'Subtasks track small pieces of work that are part of a larger task.', 'Subtask', true);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10134, 'As tarefas monitoram partes pequenas e distintas do trabalho.', 'Tarefa', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10135, 'Os epics acompanham conjuntos de erros, histórias e tarefas relacionados.', 'Epic', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10136, 'As subtarefas acompanham partes pequenas de um trabalho que pertencem a uma tarefa maior.', 'Subtarefa', true);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10137, 'As tarefas monitoram partes pequenas e distintas do trabalho.', 'Tarefa', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10138, 'Os epics monitoram coleções de tarefas, histórias e bugs relacionados.', 'Epic', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10139, 'As subtarefas monitoram pequenas partes do trabalho que fazem parte de uma tarefa maior.', 'Subtarefa', true);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10140, 'As tarefas monitoram partes pequenas e distintas do trabalho.', 'Tarefa', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10141, 'Epics track collections of related bugs, stories, and tasks.', 'Epic', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10142, 'Subtasks track small pieces of work that are part of a larger task.', 'Subtask', true);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10143, 'Stories track functionality or features expressed as user goals.', 'Story', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10150, 'Document and share incident learning.', '[System] Post-incident review', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10163, 'Submit an onboarding request for a new hire.', 'Employee onboarding', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10165, 'Request received from your email support channel.', 'Emailed request', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10167, '', 'Performance', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10174, 'Tasks track small, distinct pieces of work.', 'Task', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10175, 'Os epics acompanham conjuntos de erros, histórias e tarefas relacionados.', 'Epic', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10176, 'As subtarefas acompanham partes pequenas de um trabalho que pertencem a uma tarefa maior.', 'Subtarefa', true);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10183, 'Tasks track small, distinct pieces of work.', 'Task', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10184, 'Os epics monitoram coleções de tarefas, histórias e bugs relacionados.', 'Epic', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10185, 'As subtarefas monitoram pequenas partes do trabalho que fazem parte de uma tarefa maior.', 'Subtarefa', true);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10186, 'Tasks track small, distinct pieces of work.', 'Task', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10187, 'Os epics monitoram coleções de tarefas, histórias e bugs relacionados.', 'Epic', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10188, 'As subtarefas monitoram pequenas partes do trabalho que fazem parte de uma tarefa maior.', 'Subtarefa', true);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10189, '', 'Cliente Onboarding', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10198, '', 'Ideia', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10199, '', 'Alert', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10200, '', 'SRE Devops', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10201, '', 'User Flow', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10203, 'Sub-impl', 'Sub-impl', true);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10204, '', 'Sub-test', true);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10208, 'A person who has been employed.', 'Employee', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10209, '', 'Forms', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10215, '', 'Sub-int', true);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10220, 'Stories track functionality or features expressed as user goals.', 'Story', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10221, '', 'Sub-change', true);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10222, '', 'Non Functional Task', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10223, '', 'Improvement', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10224, '', 'Block', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10232, 'Tasks track small, distinct pieces of work.', 'Task', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10233, 'Epics track collections of related bugs, stories, and tasks.', 'Epic', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10234, 'Subtasks track small pieces of work that are part of a larger task.', 'Subtask', true);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10235, '', 'Spike', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10236, '', 'Theme', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10237, '', 'Atribuição de Limite', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10238, '', 'Cadastro', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10239, '', 'Atualização', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10241, '', 'Realocação de Limite', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10242, '', 'Candidate', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10245, 'Submit an offboarding request for an employee leaving the company.', 'Employee offboarding', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10246, '', 'Access Request', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10248, '', 'Kudos', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10249, '', 'Cliente Produção', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10250, '', 'Sub-Dúvidas', true);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10251, '', 'Sub-Cadastro', true);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10252, '', 'Sub-Análise', true);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10253, 'Discovery idea', 'Idea', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10254, '', 'Análise de Crédito', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10255, '', 'Monitoramento', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10257, '', 'Time', false);
INSERT INTO public.issue_types (id, description, name, subtask) VALUES (10261, '', 'Retrospective', false);
