INSERT INTO public.statuses (id, name, status_category_id) VALUES (1, 'Open', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (3, 'In Progress', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (4, 'Grooming Técnico', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (5, 'Available', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (6, 'Closed', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10001, 'Backlog', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10002, 'Selected for Development', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10003, 'Done', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10004, 'Canceled', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10005, 'Bloqueado', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10007, 'Test', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10008, 'Declined', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10009, 'Waiting for support', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10010, 'Waiting for customer', 1);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10011, 'Pending', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10012, 'Resolved', 1);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10013, 'DOING - Data Underst.', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10014, 'Canceled', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10015, 'Escalated', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10016, 'Waiting for System Approval', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10017, 'DOING - Modeling', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10018, 'Planning', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10019, 'DOING - Evaluation', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10020, 'Implementing', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10021, 'Peer review / change manager approval', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10022, 'Em Progresso', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10023, 'Done', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10024, 'Under investigation', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10025, 'Under review', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10026, 'Reopened', 1);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10027, 'Data Prioritized', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10031, 'Data Backlog', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10034, 'Data Delivered', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10035, 'Data Canceled', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10036, 'Data Blocked', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10043, 'Core Backlog', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10044, 'Core Priorizado', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10045, 'Core Dev', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10046, 'Core Homologacao', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10047, 'Core Concluido', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10048, 'Core Entregue ao Cliente', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10049, 'Core Bloqueado', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10050, 'Core Cancelado', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10051, 'In Progress', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10052, 'Done', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10056, 'Awaiting implementation', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10057, 'Canceled', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10062, 'Declined', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10063, 'Aguardando pelo suporte', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10064, 'Aguardando cliente', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10065, 'Itens Pendentes', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10066, 'Resolved', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10067, 'Escalado', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10068, 'Fechada', 1);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10069, 'Aguardando autorização', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10071, 'Planejamento', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10072, 'Aguardando implementação', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10073, 'Implementando', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10075, 'Triagem', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10077, 'Concluído(a)', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10078, 'Sob investigação', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10079, 'Sob análise', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10080, 'Reaberto', 1);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10081, 'Itens concluídos', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10083, 'PRONTO PARA DEV', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10099, 'Core Homologação interna', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10100, 'Core Grooming Técnico', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10101, 'Lançamento retirado', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10103, 'In Monitoring', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10104, 'Em Proposta Técnica Sinqia', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10120, 'Para deploy', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10121, 'Pronto para deploy', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10125, 'To do', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10128, 'In Review', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10131, 'Data Grooming', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10132, 'Data TO-DO', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10133, 'Data On-Going', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10134, 'Data User Testing', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10138, 'BACKLOG', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10139, 'In Progress', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10140, 'Done', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10141, 'Planejado', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10142, 'Prioritized', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10143, 'Pronto pra dev', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10170, 'To Do', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10171, 'In Progress', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10172, 'Done', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10173, 'BLOCK', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10174, 'Em homologação', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10175, 'Em implantação', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10176, 'Revisar', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10177, 'Autorizar', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10178, 'Falha', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10186, 'Ideação', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10187, 'Prototipo', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10189, 'Pronto', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10190, 'Refinamento Técnico', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10191, 'Documentação', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10201, 'EM DESENVOLVIMENTO', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10204, 'REFINADO', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10205, 'EM QA', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10214, 'Trabalho em andamento', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10229, 'Cancelled', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10231, 'Priorizado', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10232, 'Design', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10234, 'Refinamento', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10235, 'Backlog', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10236, 'BLOQUEADO', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10237, 'FINALIZADO', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10238, 'EM DESENVOLVIMENTO', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10244, 'EM DELIVERY', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10245, 'Bloqueado', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10246, 'PRONTO PARA QA', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10247, 'PRONTO DEPLOY', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10248, 'Pronto', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10250, 'To Do', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10251, 'In Progress', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10252, 'Done', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10255, 'To Do', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10256, 'In Progress', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10257, 'Done', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10258, 'Bloqueado', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10259, 'Backlog', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10260, 'In Progress', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10261, 'Done', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10262, 'Pronto para dev', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10263, 'Desenvolvimento', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10264, 'QA (Testes)', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10268, 'EM VALIDAÇÃO', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10269, 'Aprovado', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10271, 'Closed', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10273, 'Authorize', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10274, 'Failed', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10276, 'Awaiting approval', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10277, 'Draft', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10278, 'Published', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10279, 'Aprovação Técnica Bexs', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10280, 'Aguardando Início Sinqia', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10281, 'Em Proposta Comercial Sinqia', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10282, 'Aprovação Comercial Bexs', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10283, 'Aguardando homologação', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10291, 'Done', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10292, 'WON''T DO', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10293, 'Em Andamento Sinqia', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10294, 'Em Andamento Bexs', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10299, 'Aguardando Abastecimento', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10300, 'CODE REVIEW', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10301, 'Discover', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10302, 'Define', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10304, 'Validação', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10305, 'To Do', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10306, 'In Progress', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10307, 'Done', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10308, 'EM TESTE', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10309, 'EM CODE REVIEW', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10310, 'PRONTO PARA REFINAMENTO', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10311, 'Pending', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10317, 'EM REFINAMENTO TECNICO', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10325, 'To Do', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10326, 'In Progress', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10327, 'Done', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10328, 'To Do', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10329, 'In Progress', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10330, 'Done', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10331, 'Blocked', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10333, 'Em Análise', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10339, 'Aguardando documentação adicional', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10350, 'Rotina de Trabalho', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10351, 'Em Deploy', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10353, 'In Validation', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10354, 'BACKLOG', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10356, 'Aguardando Atendimento', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10357, 'Aguardando Mudança', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10358, 'Alterado pelo solicitante', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10359, 'Aplicada solução de contorno', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10360, 'Em atendimento', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10361, 'Pendente Análise de Viabilidade', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10362, 'Pendente Cliente', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10363, 'Pendente Comercial', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10364, 'Pendente Fornecedor', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10365, 'Registrado', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10366, 'Experiência Identificada', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10367, 'Experiência Entendida', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10368, 'Experiência Concebida', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10369, 'Experiência Detalhada', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10370, 'Design Visual Concebido', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10371, 'Refinamento de Negócio', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10372, 'Refinamento de Negócio Finalizado', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10373, 'Approved - Waiting for Support', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10374, 'DENIED - WAITING FOR SUPPORT', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10376, 'Waiting for supplier', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10377, 'In QA', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10378, 'In Refinement', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10379, 'In Development', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10380, 'Ready to Production', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10384, 'Signed Offer', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10386, 'IT Provisioning', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10387, 'Papo RH', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10388, 'Onboarding finish', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10389, 'In Identification', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10396, 'Aguardando contratante', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10398, 'Aguardando Aprovação Compliance', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10401, 'Stand By', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10412, 'On Approval', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10417, 'Pronto Para Refinamento Técnico', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10418, 'Pronto Para Refinamento de Negócio', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10419, 'Imersão câmbio', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10420, 'Imersão Produtos', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10421, 'Papo com o ceo', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10423, 'PRIORIZADO', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10424, 'CANCELADO', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10425, 'A FAZER', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10426, 'Reprovado', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10441, 'Solicitação Rejeitada', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10442, 'Solicitação Retornada', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10444, 'In Discovery', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10445, 'Standby', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10446, 'WON''T DO', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10447, 'To Do', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10448, 'In Progress', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10449, 'Done', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10451, 'Blocked', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10454, 'Nova Solicitação', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10455, 'Todo - DAY', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10456, 'Aguardando Aprovação Financeiro', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10476, 'Ready to Review', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10477, 'Ready to QA', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10481, 'Aguardando Análise Jurídico', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10483, 'Ready to deploy', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10484, 'Ready to Dev', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10485, 'Waiting Approval', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10486, 'Waiting for approval', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10492, 'In Design', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10493, 'Aguardando Aprovação Gestor', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10494, 'Aguardando Análise Compliance', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10501, 'Produção', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10502, 'Done', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10503, 'Discovery', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10504, 'Parking lot', 2);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10505, 'Ready for delivery', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10506, 'Delivery', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10507, 'Impact', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10509, 'Cancel', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10510, 'Homologation', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10511, 'Integration', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10512, 'Pre-Integration', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10513, 'Commercial Refinement', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10514, 'Implantation', 4);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10515, 'Production', 3);
INSERT INTO public.statuses (id, name, status_category_id) VALUES (10518, 'Aguardando Análise Cyber', 2);
